version: "3.9"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_COMPOSE_IMAGE_NAME}
    container_name: ${DOCKER_COMPOSE_CONTAINER_NAME}
    ports:
      - ${DOCKER_COMPOSE_LISTENING_PORT}:80
      - 443:443
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx-https.conf:/etc/nginx/conf.d/default.conf
      - ${FULLCHAIN_PEM_PATH}:/etc/nginx/ssl/fullchain.pem
      - ${PRIVATE_KEY_PATH}:/etc/nginx/ssl/privkey.pem