version: "3.9"

services:
    web:
        image: nginx:alpine
        ports:
            - ${DOCKER_COMPOSE_LISTENING_PORT}:80
        volumes:
            - ./out:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
